### ISSUE TITLE
V2: Add RGB values to the different portals

### ISSUE THREAD

**Issue by Brahmanathaswami** [Himalayan-Academy/Siva-Siva-App#4]
# Tasks 
- [ ] Dig out the RGB values from Indesign
- [ ] research how David sets background colors on rows [behavior_SivaSivaPortal script](https://github.com/Himalayan-Academy/Siva-Siva-App/blob/master/behaviors/behavior_InitSivaSivaProject.livecodescript)
- [ ] add RGB values to the model_SivaSiva.json file that defines portal data

**Comment by Brahmanathaswami** [comment]
done
